config/routes.rb
Rails.application.routes.draw do
  resources :qr_codes, only: [:new, :create]
    # root to: "qr_codes#new"

  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'dashboard/main'

  devise_for :users
  get 'basepage/index'
  root "basepage#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/basepage_controller.rb
class BasepageController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def main
  end
end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  def new
  end

  def create
    @qr = RQRCode::QRCode.new( qr_code_params[:text], size: 4)
  end

private
  def qr_code_params
    params.require(:qr_code).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basepage_helper.rb
module BasepageHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/views/basepage/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>New Age - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/vendor/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="assets/vendor/device-mockups/device-mockups.min.css">

    <!-- Theme CSS -->
    <link href="assets/new-age.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Vital</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#download">Dashboard</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#features">Learn More</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-sm-7">
                    <div class="header-content">
                        <div class="header-content-inner">


<!-- ========================================================================================================== -->
<% if user_signed_in? %>
<h1>Hello, <strong><%= current_user.email %></strong>! </h1>
  <%= link_to 'Dashboard', dashboard_main_path, :class => "btn btn-outline btn-xl page-scroll" %>
  <%= link_to 'Edit profile', edit_user_registration_path %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
<% else %>
<h1>Vital Health-Tech Services, revolutionizing healthcare in third world countries by providing a secure network for care establishments to gather patient data.  </h1>
 <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-outline btn-xl page-scroll" %>
  <%= link_to "Login", new_user_session_path, :class => "btn btn-outline btn-xl page-scroll" %>
<% end %>
<!-- =============================================================================================== -->

                        </div>
                    </div>
                </div>
                <!-- <div class="col-sm-5">
                    <div class="device-container">
                        <div class="device-mockup iphone6_plus portrait white">
                            <div class="device">
                                <div class="screen">
                                    Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else!
                                    <img src="assets/demo-screen-1.jpg" class="img-responsive" alt="">
                                </div>
                                <div class="button">
                                    You can hook the "home button" to some JavaScript events or just remove it
                                </div>
                            </div>
                        </div>
                    </div>
                </div> -->
            </div>
        </div>
    </header>



    <section id="contact" class="contact bg-primary">
        <div class="container">
            <h2>We <i class="fa fa-heart"></i> new friends!</h2>
            <ul class="list-inline list-social">
                <li class="social-twitter">
                    <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li class="social-facebook">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                </li>
                <li class="social-google-plus">
                    <a href="#"><i class="fa fa-google-plus"></i></a>
                </li>
            </ul>
        </div>
    </section>

    <footer>
        <div class="container">
            <p>&copy; 2016 Start Bootstrap. All Rights Reserved.</p>
            <ul class="list-inline">
                <li>
                    <a href="#">Privacy</a>
                </li>
                <li>
                    <a href="#">Terms</a>
                </li>
                <li>
                    <a href="#">FAQ</a>
                </li>
            </ul>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="assets/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="assets/new-age.min.js"></script>

</body>

</html>

app/views/dashboard/main.html.erb
<h1> Main Patient Dash !<h1>


  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>




<a class="waves-effect waves-light btn">add patient</a>


<a class="waves-effect waves-light btn">library</a>


<a class="waves-effect waves-light btn">settings</a>


<!-- Might need to be removed. Rails d controller dashboard  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vital</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
          <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <%= yield %>

  </body>
</html>

app/views/qr_codes/create.html.erb
<table class="qr-code">
<% @qr.modules.each_index do |x| %>
  <tr>
  <% @qr.modules.each_index do |y| %>
   <% if @qr.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>
<br />
<br />
<%= link_to "New QR Code", new_qr_code_path %>

app/views/qr_codes/new.html.erb
<%= form_for :qr_code, url: qr_codes_path do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>